In [1]:
# Импорт библиотек
import numpy
import pandas as pd

# Импорт matplotlib - не нужен, на всякий случай

import matplotlib
import matplotlib.pyplot as plt
matplotlib.style.use('ggplot')
%matplotlib inline


# Импорт нужного из keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils

from keras import optimizers
from keras import initializers



Using TensorFlow backend.


In [2]:
# Задаем рабочую папку

import os
os.chdir("C:/Users/USER/Documents/Python/_AD_Python_part_4_NNet/03_NNet_Classification")


FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'C:/Users/USER/Documents/Python/_AD_Python_part_4_NNet/03_NNet_Classification'

In [3]:
# Импорт данных
wine = pd.read_csv('Wine.txt', sep='\t', header=0)


In [4]:
#  Все хорошо?
wine.head()

Input1  Input2  Input3  Input4  Input5  Input6  Input7  Input8  Input9  \
0   14.23    1.71    2.43    15.6     127    2.80    3.06    0.28    2.29   
1   13.20    1.78    2.14    11.2     100    2.65    2.76    0.26    1.28   
2   13.16    2.36    2.67    18.6     101    2.80    3.24    0.30    2.81   
3   14.37    1.95    2.50    16.8     113    3.85    3.49    0.24    2.18   
4   13.24    2.59    2.87    21.0     118    2.80    2.69    0.39    1.82   

   Input10  Input11  Input12  Input13  Desired1(3)  
0     5.64     1.04     3.92     1065            0  
1     4.38     1.05     3.40     1050            0  
2     5.68     1.03     3.17     1185            0  
3     7.80     0.86     3.45     1480            0  
4     4.32     1.04     2.93      735            0

In [5]:
#  Отклик сбалансирован?
wine['Desired1(3)'].value_counts(normalize=True)

2    0.398876
0    0.331461
1    0.269663
Name: Desired1(3), dtype: float64

In [6]:
#   Разделяем предикторы и отклик
# Отклик - группирующая переменная -  вектор y
y = wine['Desired1(3)']
# Предикторы - таблица X
X = wine.drop('Desired1(3)', axis=1)

In [7]:
обучающей выборки

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=12345,
                                                    # доля объёма тестового множества
                                                    test_size=0.33)

In [8]:
#  Все хорошо?
#  X_train.head()
#  X_test.head()
#  y_train.head()
#  y_test.head()




In [9]:
#  Преобразование pandas dataframe в numpy array
X_train = X_train.values
X_test = X_test.values
y_train = y_train.values
y_test = y_test.values



In [10]:
# Больше 2-х классов
# Классы не упорядочены
y_train_bin = np_utils.to_categorical(y_train)

y_test_bin = np_utils.to_categorical(y_test)

In [11]:
# Почему не работает?
# y_train_bin.head()

In [12]:
y_train_bin[0:5]

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [13]:
i = 1337

In [14]:

i = i +1

# init_2 = initializers.TruncatedNormal(mean=0.0, stddev=0.05, seed=i)
init_2 = initializers.TruncatedNormal(mean=0.0, stddev=0.5, seed=i)
init_3 = initializers.Constant(value = 1e-3)



# Описание архитектуры сети
model = Sequential()
model.add(Dense(9, input_dim=13, activation='relu', kernel_initializer=init_2, bias_initializer=init_3))
model.add(Dense(10, activation='relu', kernel_initializer=init_2, bias_initializer=init_3))
model.add(Dense(3, activation='softmax', kernel_initializer=init_2, bias_initializer=init_3))


# Компиляция модели
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


#  Обучение модели
model.fit(X_train, y_train_bin, epochs=300, batch_size=10)


Epoch 1/300
119/119 [==============================] - 1s 5ms/step - loss: 4.8261 - acc: 0.6639
Epoch 2/300
119/119 [==============================] - 0s 210us/step - loss: 4.9577 - acc: 0.6555
Epoch 3/300
119/119 [==============================] - 0s 227us/step - loss: 4.7070 - acc: 0.6807
Epoch 4/300
119/119 [==============================] - 0s 193us/step - loss: 4.7479 - acc: 0.6723
Epoch 5/300
119/119 [==============================] - 0s 168us/step - loss: 4.7108 - acc: 0.6807
Epoch 6/300
119/119 [==============================] - 0s 210us/step - loss: 4.6940 - acc: 0.6639
Epoch 7/300
119/119 [==============================] - 0s 168us/step - loss: 4.6861 - acc: 0.6807
Epoch 8/300
119/119 [==============================] - 0s 143us/step - loss: 4.6897 - acc: 0.6807
Epoch 9/300
119/119 [==============================] - 0s 227us/step - loss: 4.6576 - acc: 0.6807
Epoch 10/300
119/119 [==============================] - 0s 210us/step - loss: 4.6597 - acc: 0.6723
Epoch 11/300
119/119 

119/119 [==============================] - 0s 185us/step - loss: 4.3756 - acc: 0.7143
Epoch 165/300
119/119 [==============================] - 0s 185us/step - loss: 4.3861 - acc: 0.7143
Epoch 166/300
119/119 [==============================] - 0s 202us/step - loss: 4.3820 - acc: 0.7143
Epoch 167/300
119/119 [==============================] - 0s 185us/step - loss: 4.3883 - acc: 0.7059
Epoch 168/300
119/119 [==============================] - 0s 176us/step - loss: 4.4228 - acc: 0.6891
Epoch 169/300
119/119 [==============================] - 0s 252us/step - loss: 4.3998 - acc: 0.6975
Epoch 170/300
119/119 [==============================] - 0s 176us/step - loss: 4.4240 - acc: 0.6891
Epoch 171/300
119/119 [==============================] - 0s 210us/step - loss: 4.4705 - acc: 0.6807
Epoch 172/300
119/119 [==============================] - 0s 328us/step - loss: 4.3914 - acc: 0.7059
Epoch 173/300
119/119 [==============================] - 0s 193us/step - loss: 4.4112 - acc: 0.7059
Epoch 174/300


119/119 [==============================] - 0s 177us/step - loss: 4.3888 - acc: 0.7059
Epoch 247/300
119/119 [==============================] - 0s 185us/step - loss: 4.4221 - acc: 0.6975
Epoch 248/300
119/119 [==============================] - 0s 202us/step - loss: 4.3758 - acc: 0.7143
Epoch 249/300
119/119 [==============================] - 0s 143us/step - loss: 4.3856 - acc: 0.7143
Epoch 250/300
119/119 [==============================] - 0s 202us/step - loss: 4.3783 - acc: 0.7227
Epoch 251/300
119/119 [==============================] - 0s 202us/step - loss: 4.3875 - acc: 0.6975
Epoch 252/300
119/119 [==============================] - 0s 176us/step - loss: 4.3918 - acc: 0.7059
Epoch 253/300
119/119 [==============================] - 0s 218us/step - loss: 4.4254 - acc: 0.6807
Epoch 254/300
119/119 [==============================] - 0s 168us/step - loss: 4.3690 - acc: 0.7143
Epoch 255/300
119/119 [==============================] - 0s 160us/step - loss: 4.3796 - acc: 0.7227
Epoch 256/300


In [15]:
#  Оценка качества модели
scores = model.evaluate(X_test, y_test_bin)
print("\nAccuracy: %.2f%%" % (scores[1]*100))

59/59 [==============================] - 0s 2ms/step

Accuracy: 67.80%


In [16]:
print(scores)

[4.480061522984909, 0.6779660936129295]


In [17]:
# Применение модели
predictions_1 = model.predict(X_test)
# Округление распознанных вероятностей
# rounded = [round(x[0]) for x in predictions]
# print(rounded)

In [18]:
print(predictions_1[0:5])

[[7.7619463e-02 6.3421873e-36 9.2238051e-01]
 [1.4345467e-01 0.0000000e+00 8.5654527e-01]
 [4.7291735e-01 0.0000000e+00 5.2708256e-01]
 [9.8923862e-01 0.0000000e+00 1.0761364e-02]
 [4.4332998e-04 0.0000000e+00 9.9955660e-01]]


Вместо ручной ре-инициализации пишем бесконечный цикл

Бесконечный цикл очень опасен. Особенно на платных ресурсах, например в облаке.

In [ ]:
while True:
    i = i +1

    init_2 = initializers.TruncatedNormal(mean=0.0, stddev=0.5, seed=i)
    init_3 = initializers.Constant(value = 1e-3)

    # Creating a model
    model = Sequential()
    model.add(Dense(9, input_dim=13, activation='relu', kernel_initializer=init_2, bias_initializer=init_3))
    model.add(Dense(10, activation='relu', kernel_initializer=init_2, bias_initializer=init_3))
    model.add(Dense(3, activation='softmax', kernel_initializer=init_2, bias_initializer=init_3))


    # Compiling model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

    # Training a model
    model.fit(X_train, y_train_bin, epochs=300, batch_size=10)

    # evaluate the model
    scores = model.evaluate(X_train, y_train)
    print('i=',  i, scores)
    if scores[1]>0.90:
        break
    
    
    
  

In [20]:
# Уточним модель - model2



# model3 = Sequential()
# model3.add(Dense(9, input_dim=13, activation='relu', kernel_initializer='random_uniform', bias_initializer='zeros'))
# model3.add(Dense(10, activation='relu', kernel_initializer='random_uniform', bias_initializer='zeros' ))
# model3.add(Dense(3, activation='softmax', kernel_initializer='random_uniform', bias_initializer='zeros'))

init_2 = initializers.TruncatedNormal(mean=0.0, stddev=0.05, seed=12345)
init_3 = initializers.Constant(value = 1e-3)

model3 = Sequential()
model3.add(Dense(9, input_dim=13, activation='relu', kernel_initializer=init_2, bias_initializer=init_3))
model3.add(Dense(10, activation='relu', kernel_initializer=init_2, bias_initializer=init_3 ))
model3.add(Dense(3, activation='softmax', kernel_initializer=init_2, bias_initializer=init_3))


#  kernel_initializer='random_uniform', bias_initializer='zeros'))


# Compiling model

sgd2 = optimizers.SGD(lr=0.02, decay=1e-6, momentum=0.8, nesterov=True)
model3.compile(loss='categorical_crossentropy', optimizer=sgd2, metrics=['accuracy'])

#  model2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


# Training a model
model3.fit(X_train, y_train_bin, epochs=300, batch_size=10)


Epoch 1/300
119/119 [==============================] - 1s 6ms/step - loss: 1.1904 - acc: 0.4286
Epoch 2/300
119/119 [==============================] - 0s 258us/step - loss: 1.0904 - acc: 0.4118
Epoch 3/300
119/119 [==============================] - 0s 221us/step - loss: 1.0860 - acc: 0.4118
Epoch 4/300
119/119 [==============================] - 0s 218us/step - loss: 1.0866 - acc: 0.4118
Epoch 5/300
119/119 [==============================] - 0s 219us/step - loss: 1.0855 - acc: 0.4118
Epoch 6/300
119/119 [==============================] - 0s 437us/step - loss: 1.0852 - acc: 0.4118
Epoch 7/300
119/119 [==============================] - 0s 245us/step - loss: 1.0844 - acc: 0.4118
Epoch 8/300
119/119 [==============================] - 0s 264us/step - loss: 1.0849 - acc: 0.4118
Epoch 9/300
119/119 [==============================] - 0s 278us/step - loss: 1.0851 - acc: 0.4118
Epoch 10/300
119/119 [==============================] - 0s 177us/step - loss: 1.0854 - acc: 0.4118
Epoch 11/300
119/119 

119/119 [==============================] - 0s 240us/step - loss: 1.0855 - acc: 0.4118
Epoch 166/300
119/119 [==============================] - 0s 268us/step - loss: 1.0857 - acc: 0.4118
Epoch 167/300
119/119 [==============================] - 0s 279us/step - loss: 1.0838 - acc: 0.4118
Epoch 168/300
119/119 [==============================] - 0s 239us/step - loss: 1.0837 - acc: 0.4118
Epoch 169/300
119/119 [==============================] - 0s 198us/step - loss: 1.0856 - acc: 0.4118
Epoch 170/300
119/119 [==============================] - 0s 333us/step - loss: 1.0845 - acc: 0.4118
Epoch 171/300
119/119 [==============================] - 0s 375us/step - loss: 1.0848 - acc: 0.4118
Epoch 172/300
119/119 [==============================] - 0s 273us/step - loss: 1.0847 - acc: 0.4118
Epoch 173/300
119/119 [==============================] - 0s 433us/step - loss: 1.0840 - acc: 0.4118
Epoch 174/300
119/119 [==============================] - 0s 248us/step - loss: 1.0850 - acc: 0.4118
Epoch 175/300


In [21]:
# evaluate the model
scores = model3.evaluate(X_test, y_test_bin)
print("\nAccuracy: %.2f%%" % (scores[1]*100))

59/59 [==============================] - 0s 967us/step

Accuracy: 37.29%


In [ ]:
# calculate predictions
predictions_3 = model3.predict(X_test)
# round predictions
# rounded = [round(x[0]) for x in predictions]
# print(rounded)

In [ ]:
print(predictions_3[0:5])

In [ ]:
# Модель, где принимается инициализация по умолчанию
#  

model2 = Sequential()
model2.add(Dense(9, input_dim=13, activation='relu'))
model2.add(Dense(10, activation='relu' ))
model2.add(Dense(3, activation='softmax'))


# Compiling model

sgd2 = optimizers.SGD(lr=0.02, decay=1e-6, momentum=0.8, nesterov=True)
model2.compile(loss='categorical_crossentropy', optimizer=sgd2, metrics=['accuracy'])

#  model2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


# Training a model
model2.fit(X_train, y_train_bin, epochs=300, batch_size=10)


In [ ]:
# evaluate the model
scores2 = model2.evaluate(X_test, y_test_bin)
print("\nAccuracy: %.2f%%" % (scores2[1]*100))

In [ ]:
# calculate predictions
predictions = model2.predict(X_test)
# round predictions
# rounded = [round(x[0]) for x in predictions]
# print(rounded)

In [ ]:
print(predictions[0:5])